server:
  port: 8888
spring:
  profiles:
    active: native
#  cloud:
#    config:
#      server:
##        git:
##          uri: https://github.com/nghiabeoniamey/microservices-config-server
#        native:
#          search-locations: classpath:/config
#        encrypt:
#          enabled: true
logging:
  level:
    root: info
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){blue} %clr(${LOG_LEVEL_PATTERN:-%5p}) %m%n"