server:
  port: 0
  forward-headers-strategy: framework

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){blue} %clr([%X{traceId:-},%X{spanId:-}]){cyan} %clr(${LOG_LEVEL_PATTERN:-%5p}) %m%n"
  level:
    root: INFO
  logstash:
    enabled: true
management:
  tracing:
    sampling:
      probability: 1.0  # 100% trace, chỉ dùng dev/test
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans