server:
  port: 8061

eureka:
  renewalPercentThreshold: 0.85
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){blue} %clr(${LOG_LEVEL_PATTERN:-%5p}) %m%n"

management:
  tracing:
    sampling:
      probability: 1.0  # 100% trace, chỉ dùng dev/test
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans